AZURE IMAGE BUILDER
===================
// Metadata:
:description: Como crear imagenes propias para el Stratio cloud-provisioner en Azure.
:keywords: azure, aks, image, builder, stratio, cloud-provisioner
// Settings:
// Deshabilitar el modo de compatibilidad
:compat-mode!:
// Deshabilitar la fecha de actualización
:last-update-label!:
// Habilitamos el uso de iconos
:icons: font
// Sobreescritura de la fuente de los iconos
:icon-set: fa
// Definimos el directorio de imagenes
:imagesdir: ../images
// Refs:
:url-project: https://asciidoctor.org
:url-docs: {url-project}/docs
:url-issues:  https://github.com/asciidoctor/asciidoctor
:img-ci: https://github.com/asciidoctor/asciidoctor/workflows/CI/badge.svg
:url-antora: https://docs.antora.org/antora/latest/asciidoc/asciidoc/
// Tabla de contenidos
:toc: left
:toclevels: 6
:toc-title: 🛠️ Azure Image Builder
:source-highlighter: rouge
:rouge-style: monokai

== Introducción

Image Builder se puede utilizar para crear imágenes destinadas a su uso con proveedores de CAPI de Kubernetes. Cada proveedor tiene su propio formato de imágenes con el que puede trabajar. Por ejemplo, las instancias de AWS utilizan AMI.

🔗 https://image-builder.sigs.k8s.io/capi/capi.html[Kubernetes Image Builder]

== Prerequisitos

=== Globales
Packer y Ansible se utilizan para construir estas imágenes. Esta herramienta se ha bifurcado y ampliado del proyecto Wardroom.

Versión del empaquetador >= 1.6.0
Complemento de Goss para la versión de Packer >= 1.2.0
Versión de Ansible >= 2.10.0
Si los archivos binarios necesarios no están presentes, se pueden instalar en images/capi/.bin con el comando make deps. Este directorio deberá agregarse a su $PATH.

== Imágenes Disponibles

🔗 https://portal.azure.com/#@asistemasstratio.onmicrosoft.com/resource/subscriptions/6e2a38cd-ef16-47b3-a75e-5a4960cedf65/resourceGroups/capz/overview[VM image definition]


== Configuraciones de la imagen

Para modificar la configuración de la imagen, puede editar el archivo _images/capi/packer/azure/ubuntu-<osversion>.json_.

Los parámetros de configuración se pueden encontrar en la documentación de Packer.

🔗 https://image-builder.sigs.k8s.io/capi/capi.html#customization[Image build customization]


[TIP]
====
📂 *Version de Kubernetes*
[%autowidth]

Hay que editar el fichero _images/capi/packer/config/kubernetes.json_
[%hardbreaks]
🔗 https://kubernetes.io/releases/[Kubernetes releases]

|===
| *crictl_version* | 1.26.1 | Version de las critools
| *kubernetes_deb_version* | 1.26.8-00 | Version de kubernetes para Debian
| *kubernetes_rpm_version* | 1.26.8-0 | Versión de kubernetes para RPM
| *kubernetes_semver* | 1.26.8 | Versión semántica de Kubernetes que se instalará en la imagen
| *kubernetes_series* | 1.26 | Versión de la serie de Kubernetes que se instalará en la imagen
|===

📂 *Version de las critools*
[%autowidth]
La versión de las critools tiene que ir pareja con la versión de kubernetes que estemos usando.
[%hardbreaks]
🔗 https://github.com/kubernetes-sigs/cri-tools/tags[Critools releases]

|===
| *crictl version* | *kubernetes version*
| 1.26.1 | 1.24, 1.25, 1.26
| 1.27.1 | 1.27
| 1.28.0 | 1.28
|===

📂 *Parámetros del kernel*
[%autowidth]
Hay que editar el fichero _ansible/roles/node/tasks/main.yml_ y dentro editar la tarea con el nombre '_Set and persist kernel params_' para añadir vm.max_map_count con valor 262144

[source,yaml]

- name: Set and persist kernel params
  sysctl:
    name: "{{ item.param }}"
    value: "{{ item.val }}"
    state: present
    sysctl_set: yes
    sysctl_file: "{{ sysctl_conf_file }}"
    reload: yes
  loop:
    - { param: net.bridge.bridge-nf-call-iptables, val: 1 }
    - { param: net.bridge.bridge-nf-call-ip6tables, val: 1 }
    - { param: net.ipv4.ip_forward, val: 1 }
    - { param: net.ipv6.conf.all.forwarding, val: 1 }
    - { param: net.ipv6.conf.all.disable_ipv6, val: 0 }
    - { param: net.ipv4.tcp_congestion_control, val: bbr }
    - { param: vm.overcommit_memory, val: 1 }
    - { param: kernel.panic, val: 10 }
    - { param: kernel.panic_on_oops, val: 1 }
    - { param: fs.inotify.max_user_instances, val: 8192 }
    - { param: fs.inotify.max_user_watches, val: 524288 }
    - { param: vm.max_map_count, val: 262144 }

====

== Construcción de la imagen

. Exportar los datos de la subscripción de Azure en la que vamos a trabajar
[source,console]
export AZURE_SUBSCRIPTION_ID="<subscriptionID>"
export AZURE_TENANT_ID="<tenantID>"
export AZURE_LOCATION="<region>"

. Exportar el resource group que se usará para almacenar las imágenes creadas
[source,console]
export RESOURCE_GROUP_NAME="<resourceGroup>"

. Exportar las credenciales de la cuenta de servicio creadas en el paso anterior
[source,console]
export AZURE_CLIENT_ID="<clientID>"
export AZURE_CLIENT_SECRET="<clientSecret>"

. Preparar el repositorio de image-builder

.. Clonar el repositorio de image-builder si no lo tienías previamente
[source,console]
git clone https://github.com/kubernetes-sigs/image-builder.git
cd image-builder/images/capi/

.. Actualizar el repositorio de image-builder si ya lo tenías previamente
[source,console]
cd image-builder
git pull
cd images/capi/

. Instalar las dependencias necesarias para crear la imagen
[source,console]
make deps-azure

. Consultar las imágenes que podemos construir
[source,console]
make help | grep build-azure-sig

. Generar la imágen deseada
[source,console]
make build-azure-sig-ubuntu-2204

== Debug

Podemos debugear el proceso de creación de la imagen con la variable de entorno PACKER_LOG
[source,console]
export PACKER_LOG=1
