# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant box for testing kind with cgroup v2
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/34-cloud-base"
  memory = 2048
  cpus = 2
  config.vm.provider :virtualbox do |v|
    v.memory = memory
    v.cpus = cpus
  end
  config.vm.provider :libvirt do |v|
    v.memory = memory
    v.cpus = cpus
  end
  config.vm.provision "install-packages", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
    set -eux -o pipefail
    dnf install -y golang-go make kubernetes-client podman

    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker

    # Configure Podman to resolve `kindest/node` to `docker.io/kindest/node`.
    cat <<EOF > /etc/containers/registries.conf
[registries.search]
registries = ['docker.io']
EOF
    SHELL
  end
  config.vm.provision "install-kind", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
    set -eux -o pipefail
    make -C /vagrant install INSTALL_DIR=/usr/local/bin
    SHELL
  end
end
