version: "2"

run:
  timeout: 3m

linters:
  default: none

  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gochecknoinits
    - revive # replaces golint for now
    - misspell
    - unparam

  settings:
    staticcheck:
      checks:
        - all

  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      # this requires renaming all unused parameters, we'd rather leave a preferred
      # placeholder name in place when implementing an interface etc.
      # we can revisit this later, right now it's generating a lot of new warnings
      # after upgrading golangci-lint
      - linters:
          - revive
        text: "^unused-parameter: .*"
      - linters:
          - staticcheck
        path: pkg/cmd
        text: "ST1005: error strings should not be capitalized"
      - linters:
          - staticcheck
        path: images/kindnetd/cmd
        text: "ST1005: error strings should not be capitalized"

formatters:
  enable:
    - gofmt

