/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package loadbalancer

import (
	"strings"
	"testing"

	"sigs.k8s.io/kind/pkg/internal/assert"
)

func TestConfig(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name           string
		data           *ConfigData
		expectError    bool
		mustContain    []string
		mustNotContain []string
	}{
		{
			name: "basic IPv4 config",
			data: &ConfigData{
				ControlPlanePort: 6443,
				BackendServers: map[string]string{
					"kind-control-plane": "172.17.0.2:6443",
				},
				IPv6: false,
			},
			mustContain: []string{
				"# generated by kind",
				"bind *:6443",
				"kind-control-plane",
				"172.17.0.2:6443",
				"resolve-prefer ipv4",
			},
			mustNotContain: []string{
				"resolve-prefer ipv6",
				"bind :::6443",
			},
		},
		{
			name: "IPv6 config",
			data: &ConfigData{
				ControlPlanePort: 6443,
				BackendServers: map[string]string{
					"kind-control-plane": "[fc00::2]:6443",
				},
				IPv6: true,
			},
			mustContain: []string{
				"resolve-prefer ipv6",
				"bind :::6443",
			},
			mustNotContain: []string{
				"resolve-prefer ipv4",
			},
		},
		{
			name: "multiple backend servers",
			data: &ConfigData{
				ControlPlanePort: 6443,
				BackendServers: map[string]string{
					"kind-control-plane":  "172.17.0.2:6443",
					"kind-control-plane2": "172.17.0.3:6443",
					"kind-control-plane3": "172.17.0.4:6443",
				},
				IPv6: false,
			},
			mustContain: []string{
				"kind-control-plane",
				"kind-control-plane2",
				"kind-control-plane3",
			},
		},
		{
			name: "custom port",
			data: &ConfigData{
				ControlPlanePort: 8443,
				BackendServers:   map[string]string{},
				IPv6:             false,
			},
			mustContain: []string{
				"bind *:8443",
			},
		},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, err := Config(tc.data)
			assert.ExpectError(t, tc.expectError, err)
			if err != nil {
				return
			}
			for _, s := range tc.mustContain {
				if !strings.Contains(got, s) {
					t.Errorf("Config output does not contain %q\ngot:\n%s", s, got)
				}
			}
			for _, s := range tc.mustNotContain {
				if strings.Contains(got, s) {
					t.Errorf("Config output should not contain %q\ngot:\n%s", s, got)
				}
			}
		})
	}
}
