---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9191"
    prometheus.io/scrape: "true"
  name: calico-node-metrics
  namespace: calico-system
  labels:
    k8s-app: calico-node
spec:
  clusterIP: None
  selector:
    k8s-app: calico-node
  ports:
    - name: metrics-port
      port: 9191
      targetPort: 9191
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9093"
    prometheus.io/scrape: "true"
  name: calico-typha-metrics
  namespace: calico-system
  labels:
    k8s-app: calico-typha
spec:
  clusterIP: None
  selector:
    k8s-app: calico-typha
  ports:
    - name: metrics-port
      port: 9093
      targetPort: 9093
